### ISSUE TITLE
Disable displaying slides count, but keep current slide number

### ISSUE THREAD

**Issue by szpak** [gnab/remark#130]
On the slides created for multiday training sometimes it is better to not show the total number of slides (to have an ability to freely adjust course context or to not overwhelm the students :) ).

Slides count can be easily disabled with `.remark-slide-number` manipulation, but I have found it very ugly to limit number of displayed characters in CSS. It could be done in JavaScript modifying the `div` content (together with `showSlide` hook), but it would be useful to have an ability to disable slides count, e.g. in the configuration.

**Comment by jovo** [comment]
this doesn't work for me.
it seems like when i first refresh the page, it does work,
but then it gets over written.
i'm using the 'local' version of remark.

please advice...

**Comment by jovo** [comment]
of note, when i modify my local remark-latest.min.js

C.getSlideNumberFormat=I("slideNumberFormat","")

that removes the slide numbers, or i can otherwise modify it there.
but i'd rather modify it in the slide.html file.

also, i cannot turn off the incremental count option either by modifying the remark-latest.min.js file, or my slide.html file.

thanks again.
