### ISSUE TITLE
Mathjax Underscore Issues

### ISSUE THREAD

**Issue by dansteingart** [gnab/remark#140]
Perhaps this is resolved/handled, but I haven't found it after some googling.  What I'm seeing is that inline handling of subscripts in Latex is sufficient, but display math / arrays are lacking.  For example:

The following renders well:
`\( \int_{V_1}^{V_2}mVdV =  \int_{s_1}^{s_2} F_s ds \)`

While the following does not work:
$$\( \int_{V_1}^{V_2}mVdV =  \int_{s_1}^{s_2} F_s ds \)$$

This is tested against the html example in the wiki:

https://github.com/gnab/remark/wiki/LaTeX-using-MathJax

Thanks in advance.

**Comment by gnab** [comment]
Sorry for the late reply.

I'm not all that into MathJax. However, for the style wrapping / content class, it seems to work fine if you use it over multiple lines:

```
.medium[
`$$ \int_{V_1}^{V_2}mVdV =  \int_{s_1}^{s_2} F_s ds $$`
]
```

remark transforms `.medium[...]` into `<span class="medium">...</span>`, which for some reason breaks MathJax. With the extra newlines, however, a `div` tag is used instead of a `span` tag. The primary difference is that the `div` tag uses block display, as opposed to the `span` which uses inline. If you need to change this back, you an add `display: inline` to your `medium` class.

**Comment by dansteingart** [comment]
Thanks!  I gumped my way into this solution.  Thanks again for remark, it's
wonderful.
