### ISSUE TITLE
How to go offline

### ISSUE THREAD

**Issue by brunetto** [gnab/remark#194]
Hi!
Is there an easy guide on how to download everything to put it on a usb stick and go offline? 
Or, how can I go offline? (mathjax included)

**Comment by junderhill** [comment]
This is fairly easy to do, the following steps should do this..

1. Download the latest release of remark
2. Copy the remark.min.js file from the out directory into your presentation directory
3. Update your html file to point the script src for remark to the local file such as `<script src="remark.min.js">`
4. Go to [http://www.google.com/fonts](http://www.google.com/fonts) and find the three required font families adding them to your collection. You can then click 'USE' on the collection and click the download link.

![2015-03-06 09_33_17-google fonts](https://cloud.githubusercontent.com/assets/838529/6523052/e566b0f2-c3e3-11e4-885e-1f85c66d11c8.png)

![2015-03-06 09_33_30-google fonts](https://cloud.githubusercontent.com/assets/838529/6523054/e7e7bccc-c3e3-11e4-8c82-0569c44bf364.png)

5. Copy the required .ttf files to the presentation directory
6. Update the style element in the presentation html file to import the fonts. Notice the change to `@font-face` instead of import.

Your presentation HTML file will look something like this:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <style type="text/css">
      @font-face{
        font-family: 'Droid Serif';
        src: url('DroidSerif.ttf');
      }
      @font-face{
        font-family: 'Yanone Kaffeesatz';
        src: url('YanoneKaffeesatz-Regular.ttf');
      }
      @font-face{
        font-family: 'Ubuntu Mono';
        src: url('UbuntuMono-Regular.ttf');
      }

      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Ubuntu Mono'; }
    </style>
  </head>
  <body>
    <textarea id="source">

class: center, middle

# Title

---

# Agenda

1. Introduction
2. Deep-dive
3. ...

---

# Introduction

    </textarea>
    <script src="remark.min.js">
    </script>
    <script>
      var slideshow = remark.create();
    </script>
  </body>
</html>

```

My directory for the presentation now looks like this:

![2015-03-06 09_32_19-test](https://cloud.githubusercontent.com/assets/838529/6523036/bb405a1c-c3e3-11e4-94d2-e1af882553e7.png)

**Comment by brunetto** [comment]
Thanks!! Do I have to download also mathjax isn't it?

**Comment by junderhill** [comment]
Not that I can see, there's not references to it from the remark.js source and a quick test of the above seems to work fine. Where is that library mentioned? I don't recall seeing it anywhere.

**Comment by brunetto** [comment]
I need it to show equations in the presentations...

[Here](https://github.com/gnab/remark/wiki/LaTeX-using-MathJax) there's the wiki page and this is what I put at the end of the html file

```html
    <script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML&delayStartupUntil=configured" type="text/javascript"></script>
    <script type="text/javascript">
    var slideshow = remark.create({
    sourceUrl: './GM11.md',
});
		// Setup MathJax
		MathJax.Hub.Config({
			tex2jax: {
			inlineMath: [ ['$','$'], ["\\(","\\)"] ],
			skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
			extensions: ["AMSmath.js", "AMSsymbols.js", "autobold.js"]
			}
		});
		MathJax.Hub.Queue(function() {
			$(MathJax.Hub.getAllJax()).map(function(index, elem) {
				return(elem.SourceElement());
			}).parent().addClass('has-jax');
		});

		MathJax.Hub.Configured();
    </script>
```

Probably I just need to figure out from the Mathjax site how to do this.

**Comment by junderhill** [comment]
Ah ok, I would download the MathJax.js file to the presentation directory, update the script tag src to use the local one leaving the query string parameters.. Something like:

```
<script src="MathJax.js?config=TeX-AMS_HTML&delayStartupUntil=configured" type="text/javascript"></script>
```

**Comment by brunetto** [comment]
ok, thanks!!
I'll try asap.

b

**Comment by spitters** [comment]
Thanks for the nice piece of software.
Unfortunately, just downloading Mathjax.js does not work for me.

I get strangely enough. It renders correctly, but after a few seconds I get:

> [Math Processing Error]

Any ideas?

PS: are long subscripts supposed to be supported? 
```
$$x_{n+1}$$

**Comment by spitters** [comment]
It looks like a need a number of files:
```
fontdata.js -> jax/output/HTML-CSS/fonts/STIX/STIX/fontdata.js
jax.js -> jax/output/HTML-CSS/jax.js
MathJax.js
MathMenu.js
MathZoom.js
remark-latest.min.js
TeX-AMS_HTML.js
```
However, it is still unpredictable. I'll report if I have a complete solution. Meanwhile help would be appreciated.

**Comment by spitters** [comment]
There is also:
jax/output/HTML-CSS/fonts/STIX/STIX/fontdata-extra.js

Looks like installing the mathjax debian packages did the trick.

**Comment by HenrikBengtsson** [comment]
Thanks for this information in this issue; my interest in offline presentation is because I don't want to assume that I'll have internet access in the moment I'm starting my presentation (sure, it's actually when I load the presentation, but still too risky).

A small FYI, If you use [markdown-to-slides](https://github.com/partageit/markdown-to-slides) (>= 1.0.3; April 2016) to compile Markdown to HTML, it includes the content of `remark.js` in the generated HTML as:
```sh
markdown-to-slides --include-remark slides.md -o slides.html
```

It's also worth mentioning https://github.com/TalAter/UpUp, which provides generic _offline caching_ of any website content.  I haven't tried it, so I don't know how much work it is to get it working with Remark and whether it is possible to use locally (i.e. not sure if HTTPS server is needed).  Just my two cents.

**Comment by Alexander-Barth** [comment]
If you need italic or bold fonts you also need to add this:

```css
      @font-face{
        font-family: 'Droid Serif';
        src: url('Fonts/DroidSerif-Bold.ttf');
        font-weight: bold;
      }

      @font-face{
        font-family: 'Droid Serif';
        src: url('Fonts/DroidSerif-Italic.ttf');
        font-style: italic;
      }

      @font-face{
        font-family: 'Droid Serif';
        src: url('Fonts/DroidSerif-BoldItalic.ttf');
        font-weight: bold;
        font-style: italic;
      }
```

My fonts are in the `Fonts` folder. Of you need also the oblique variant you need to add them too. More info is available at http://stackoverflow.com/a/28571625.
