### ISSUE TITLE
Content inside macro not being Markdown parsed (rendered)

### ISSUE THREAD

**Issue by utdrmac** [gnab/remark#253]
I've defined my macro and HTML/MD content as follows:  http://jsfiddle.net/rk1px5t0/

The returned content is not re-parsed by Remark and I get raw asterisk characters instead of ul/li outline. Is there some method/function I can call on ```obj.outerHTML``` that will render the contents before sending back to the slide?

Am I doing the macro correctly? The idea is to return a div with user-defined height, width and css style. It negates the need for this ugliness and negates the need to have a CSS class for each 25, 50, 100, 150, etc.

```
.floater[.down100[.down100[.down50[.text16[.N[
my note contents
]]]]]]
```

**Comment by utdrmac** [comment]
Attempted to use this:

```
remark.loadFromString('markdown string')
```

Received "Uncaught ReferenceError: loadFromString is not defined"

**Comment by gnab** [comment]
The returned content is actually parsed, but markdown inside `div` tags aren't parsed (for which reason I cannot recall just now). Thus, using content classes (`.class[...]`) is a better solution - and if you have a line break inside the brackets, you will get a `div` tag, otherwise a `span` tag.

There is a `remark.convert` function that lets you parse markdown and return HTML that you can use. This is not documented and was only made available for testing some time ago:

```
>  remark.convert('# slide')
<- "<h1 id="slide">slide</h1>"
```

Also, when you call the macro, the syntax is as follows:

```
!:[name arg1, arg2, ...](context)
```

The corresponding macro definition looks like this:

```javascript
remark.macros.name = function (arg, arg2 /*, ... */) {
  // the context argument is represented by `this`
  var context = this;

  // ...
};
```

**Comment by utdrmac** [comment]
Perfect! That worked. And yes, I saw more how to correctly write the macro using ( ) syntax for the string. From what I read in the code, because I'm returning a string starting with '<div>', that doesn't get pattern matched as content or something like that and therefore isn't re-processed. But the .convert worked great. Thanks.
