### ISSUE TITLE
Presenter notes in Google Hangout

### ISSUE THREAD

**Issue by baseliners** [gnab/remark#296]
Hi - currently if I do presentation mode while in a Hangout, the presenter notes are shown in the hangout as well. Would be nice to fix this so the notes are shown to just me and only the full screen slides are shown in the Hangout. My company uses Google CFM (Chrome For Meetings) in all of our conference rooms. Thanks.

**Comment by gnab** [comment]
I'not familiar with how Hangouts/CFM works. If you clone your slideshow by pressing 'C', and share the new window using Hangouts/CFM, you can put your old window in presenter mode and not share that.

**Comment by baseliners** [comment]
Great idea! Just tried it today and it works well.. thanks!

**Comment by py9mrg** [comment]
@gnab Hello, as a side issue - is there a way to get a pointer (or the mouse cursor) to mirror between the presenter view and the cloned view? So that I can have my cloned window shared with the audience in a Google meeting - while viewing the presenter mode in another window - yet still be able to point to things in my window and they can see my pointing in theirs? If that makes sense??
