### ISSUE TITLE
Error in remarkise

### ISSUE THREAD

**Issue by fladd** [gnab/remark#301]
Can you maybe provide an example of a .md file that works?

I cannot get it to work with the simples .md file:

```
# Test

This is a test
```

I always get "Error".

**Comment by gnab** [comment]
Ping @tripu

**Comment by tripu** [comment]
@fladd, one example: [`https://github.com/tripu/Events/blob/master/2014-11-24_Fuenlabrada-Spain_URJC_W3C-tools/presentation.md`](https://github.com/tripu/Events/blob/master/2014-11-24_Fuenlabrada-Spain_URJC_W3C-tools/presentation.md).

The resulting URL in Remarkise would be: [`https://gnab.github.io/remark/remarkise?url=https://github.com/tripu/Events/blob/master/2014-11-24_Fuenlabrada-Spain_URJC_W3C-tools/presentation.md`](https://gnab.github.io/remark/remarkise?url=https://github.com/tripu/Events/blob/master/2014-11-24_Fuenlabrada-Spain_URJC_W3C-tools/presentation.md).

**Comment by tripu** [comment]
@fladd, can you tell me exactly how you're trying to use it, and maybe I can help?

**Comment by fladd** [comment]
@tripu 
1. I go to https://gnab.github.io/remark/remarkise
2. Where it says "URL of Markdown file" I post a URL of a Markdown file (e.g. http://stuff.fladd.de/slide_test.md)
3. I hit the Enter key on my keyboard
4. The page says "Error" (see attached picture)

![remarkise_error](https://cloud.githubusercontent.com/assets/2971539/13422180/48a2bef6-df93-11e5-9745-b69cf87c54e2.png)

**Comment by tripu** [comment]
@fladd: I see now what the problem is.

I'm afraid your issue is a consequence of [how the web works](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) and of what Remarkise does, specifically&hellip;

If you're using [the instance of Remarkise hosted here, on GH pages](https://gnab.github.io/remark/remarkise), you will be able to &ldquo;remarkise&rdquo; content hosted on GH without issues. But when you try to dynamically load content (in this case, a Remark document) from a *different* web site, that may or may not succeed&nbsp;&mdash;&nbsp;it depends on how that other server is configured.

When that happens, there are three things you can try:

1. Host your own copy of Remarkise on the same server that has your slides (if you control it)
2. Bring a copy of your slides over here, to GH, and render those instead
3. [Set up CORS](https://stackoverflow.com/search?q=enable+CORS+on+server) on that other server (if you control it)

I just made a few improvements to Remarkise (#312). Those changes cannot solve this problem, but hopefully they will help to understand what is happening to other users who find the same issue.
