### ISSUE TITLE
Discussion: New presentation templating

### ISSUE THREAD

**Issue by malikoth** [gnab/remark#345]
Hi!  I'm so happy I found Remark!  I'm giving a talk in a little while, and I've been using reveal.js which has lots of cool features, but writing slides in markdown and making them look nice is hard!  Remark is perfect for what I want!

However, starting out with it had a bit of a steeper curve to it than I would've liked.  I was thinking it would be nice to just have a brief discussion about the experience of starting with Remark.  Here were my specific issues:
- I didn't notice the boilerplate HTML files in the repo, otherwise I would've just cloned the repo and started from there.  The instructions in the readme say to copy and paste the boilerplate directly.
- I wanted to be able to make a quick presentation that looked like the official demo.  Took me a bit to find the `gh-pages` branch, and manually copy the CSS from there.
- I wanted my markdown in a separate file, and it took me awhile to figure out how to set that up, and remove the default slide content.
- Had to dig around before I found the right place in the wiki for configuring my presentation to taste (aspect ratio, primarily)

Yes, I know that all of those are not that hard to figure out, but each one still took me a little, and I just think they could be easier.

So, I created a [cookiecutter](https://github.com/audreyr/cookiecutter) [template](https://github.com/malikoth/cookiecutter-remarkjs) to speed up the process of starting a new presentation.  I wonder if it might be worth noting the possibility of using cookiecutter to bootstrap a presentation in the README on the front page.

Also, there's plenty of ways you can build options into the process of bootstrapping, so if anyone has any suggestions or contributions to my specific template, that'd be appreciated!  I haven't put in options for the local / remote / single modes corresponding to your existing boilerplate files yet, but I could if that were important.

**Comment by gnab** [comment]
Thanks for the great input! I am a bit overloaded with work at the moment, but feel free to edit whatever information in the wiki you think could be better, or supply pull requests to the README (or any other file for that matter) and I'll merge happily :)

Regarding your bullets, I'm not sure at what level the average remark user is in terms of using git, so I've assumed that it is only the more advanced users that actually clone the repo or even look at the files - and that the beginner / average user just follows the README instructions blissfully. But the README should for sure include the missing information, so that people like you would know at first glance rather than wasting time looking in the repo :)

**Comment by abelards** [comment]
Documented here, thanks!
https://github.com/gnab/remark/wiki/Static-Generators
