### ISSUE TITLE
Weird failure in slides splitting, \n---\n gives a <hr> and not a slide split

### ISSUE THREAD

**Issue by Naereen** [gnab/remark#351]
Hi,
First, thanks for this nice project, I like it! :clap:

I was finishing writing my first presentation with remark.js, when I encountered a blocking bug.
A lot of my slides (blocks of Markdown, separated with "``\n---\n``") get "squeezed" in one slide in the HTML output.
The [slide separator](https://github.com/gnab/remark/wiki/Markdown#slide-separators) is not understood correctly, and I have *no* idea why (the content of the first slide failing to split is probably responsible, but I don't know what causes this behavior).

For example, here is the Markdown code corresponding to the first failure in the slide splitting (line 46):
![bug_remarkjs_2](https://cloud.githubusercontent.com/assets/11994719/16628084/50dfcf7e-43b0-11e6-992d-2dfb9f89f419.png)

And here is the output (displaying a HTML ``<hr>`` instead of a slide split):
![bug_remarkjs_1](https://cloud.githubusercontent.com/assets/11994719/16628098/6022a308-43b0-11e6-8596-3b0db82c241a.png)

After this failure, all the next slides (= Markdown paragraph) are in the same slide in the HTML output, hence breaking the presentation...

If you have time to try yourself, the raw Markdown file for my slides is [here](https://raw.githubusercontent.com/Naereen/slides/master/2016_07__Python_demo_at_EPFL/slides.md), and here is a [live demo of the failing slide](http://remarkjs.com/remarkise?url=https%3A%2F%2Fraw.githubusercontent.com%2FNaereen%2Fslides%2Fmaster%2F2016_07__Python_demo_at_EPFL%2Fslides.md#3) using remarkise.
Thanks in advance!

**Comment by Naereen** [comment]
Note: I tried to use [reveal-md](https://github.com/webpro/reveal-md), and everything worked nicely, so I don't think the issue comes from something especially nasty in my Markdown file.

**Comment by junderhill** [comment]
The reason it's not separating is due to using two "back ticks" around inline code, instead of single "back ticks". I guess remark should handle this better, I would expect that two back ticks should work however in the the short term changing to single "back ticks" will fix your issue.

I changed just the first few and tested in remarkise and it fixes the problem. 
[http://remarkjs.com/remarkise?url=https://gist.githubusercontent.com/junderhill/4b4c2d931029a16ff0cd96b86ec01fd2/raw/2db885348a26feba770fa8053c9313834d7564a1/remark_351#1](http://remarkjs.com/remarkise?url=https://gist.githubusercontent.com/junderhill/4b4c2d931029a16ff0cd96b86ec01fd2/raw/2db885348a26feba770fa8053c9313834d7564a1/remark_351#1)

Do you know if two back ticks is valid mark down? I've tested on a few online markdown editors and it seems that any number of "back ticks" will produce the desired effect, so that would lead me to believe we need to handle it.

@gnab perhaps you know if it's valid syntax? If so I'll submit a pull request to fix this.

**Comment by junderhill** [comment]
It does seem that double backticks are commonly used for escaping inline code that contains a backtick.

[http://www.growingwiththeweb.com/2015/06/escaping-backtick-in-markdown.html](http://www.growingwiththeweb.com/2015/06/escaping-backtick-in-markdown.html)

**Comment by Naereen** [comment]
Hi,
Sorry for the delay.

Thanks, the issue was indeed the use of double backticks instead of simple ones.
I got this bad habit from using more reStructuredText than Markdown (in rst the simple backticks are for links...).

So thanks a lot for your reply, it fixed my slides (and now I know why remark was breaking them wrongly).

Regards.
