### ISSUE TITLE
<div> with marker class for the whole template content

### ISSUE THREAD

**Issue by szpak** [gnab/remark#402]
Remark wraps a template for a given slide with `<p>` tag(s). It is placed before a slide content and can by default a margin which move the header of that given slide away from the top border (see [here](https://github.com/gnab/remark/issues/372#issuecomment-267444321)).

As `<p>` is created for every element (an therefore first-of-type can be [tricky](https://jsfiddle.net/uquzLqwy/)) it would be good to have a `<div>` with a marker class (or anything else you think will be appropriate) for the whole template content to be used to remove a margin (or do anything else) from a template content.

**Comment by abelards** [comment]
Things look fixed in the other issue.

I personally find my way with CSS, with any kind of trick like `b:first-child` or `a > b` or even removing all margins then re-adding them when needed.

If you have trouble implementing the trick, let me know then we'll have a look and document that in the wiki.
Cheers,
