### ISSUE TITLE
Control order of appearance of elements in an incremental slide

### ISSUE THREAD

**Issue by jdumas** [gnab/remark#407]
Hi,

Let's say I have a list in an incremental slide, with an image below:

```
---
# Slide Title

- Item 1
- Item 2
- Item 3

.center[<img style="width:80%"  src="image.jpg">]
```

I want to make item 1, 2 and 3 appear incrementally (which I can do using a `--`). But I also want my picture to be shown from the beginning. If I use incremental slides, the picture will only be shown after the last element has appeared.

Would it be possible to have more fine-grained, beamer-like, control over the animations? Maybe I have missed something in the doc.

**Comment by abelards** [comment]
Hi @jdumas -- I totally understand what you need, but I would probably use a trick here:

```
<style>.fig1 { background: url('image.png') } </style>
---
# Slide with fig 1

.fig1 [

- Item 1
--

- Item 2
--

- Item 3
]
```

I'll let you find the correct background positioning you'll want in your CSS.

Also, if you wanted "sticky items" in "incremental slides", what syntax would you use?

It's been a long time since I did LaTeX and I almost never did beamer but feel free to give us examples.

Kind regards,

**Comment by jdumas** [comment]
Thanks, but this is issue is 3 years old, and I haven't really used remark.js since then =)

**Comment by abelards** [comment]
I can imagine. I'll close the ticket and reference this in the wiki as HTML/CSS trick. Cheers!
