### ISSUE TITLE
Using remark with Jekyll

### ISSUE THREAD

**Issue by pschloss** [gnab/remark#413]
Thanks for the instructions in the [wiki](https://github.com/gnab/remark/wiki/Using-with-Jekyll). I've noticed a couple of things...

1. This is more of an observation than an issue, but the formatting of the presentation.html file is pretty sensitive. The `presentation.html` file that is provided is formatted like so...

```
  <body>
    <textarea id="source">
{{ content }}
    </textarea>
```

I found that when the `{{content}}` was indented or if I put a comment preceding the mustache code, a `class: center middle` line I inserted to format the title slide was ignored. In addition the `class: center middle` line was treated as normal text and rendered at the top of the slide.

2. When using Jekyll, the markdown file needs to have a html ending. Is there a way around this? It would be nice for my markdown file to have markdown text coloring in my text editor, rather than html coloring. If I name the file `default-presentation.md` rather than `default-presentation.html` the slide deck is rendered as a single page rather than as a slide deck.

**Comment by scotthewitt** [comment]
I find it is much more robust using an separate txt file with the markdown slides in it and then using a jekyl layout to make use of it.

<body>

    <script src="https://gnab.github.io/remark/downloads/remark-latest.min.js">
    </script>
    <script>
      var slideshow = remark.create({
      sourceUrl: '{{page.presentationsource}}'
      });
    </script>
  </body>

**Comment by mconnor** [comment]
this feature is not working for me at all. I tried putting the presentation.html file in a _layouts folder on the top level of my jekyll site... and in the gem folder
/Users/me/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/minima-2.0.0/_includes

**Comment by akakeronos** [comment]
Thanks for the instruction on the wiki
I'm trying to make it run on the gitlab.com plateform and had it work on github before.
I tried locally and the errror is similar

When deploying on gitlab it is not working probably because of an obvious mistake I can't see...

1. I created a layout names [presentation.html](https://gitlab.com/rhizome-data/formations/blob/master/_layouts/presentation.html) containing the code displayed in the [wiki](https://github.com/gnab/remark/wiki/Using-with-Jekyll)
2. at the root of the jekyll site I created a [test-prez.md](https://gitlab.com/rhizome-data/formations/blob/master/test-prez.md) file containing the code displayed in the wiki

If I add the meta permalink: /test-prez/ as written in the wiki it displays a 404 error
If I remove it it works. Well the markdown is rendered as html but the slide magic doesn't happen as the --- are rendered as hr tags

Any help would be greatly appreciated :)

**Comment by abelards** [comment]
This is more of a Jekyll problem since it "wants" to transform your content.
If you don't want Jekyll to touch your markdown, you can simply tell it not to generate that.

For instance, I have done the "lowest effort possible" thing in my blog by simply using another directory: https://github.com/abelards/abelards.github.com/blob/master/talks/10mnCTO.html

With my take (Jekyll don't touch this) and the wiki's, you have two very different ways to do it, so I'll close the issue, and please let me know and reopen it if it's not enough.
Cheers,

**Comment by akakeronos** [comment]
Hi, 
Thanks for your answer. I'll try that and let you know if I manage to make it to work.
Cheers,

**Comment by ratnanil** [comment]
>  If you don't want Jekyll to touch your markdown, you can simply tell it not to generate that.

@abelards: I've looked at your example, but havent found out how you tell jekyll not to touch my markdown.. can you elaborate?

**Comment by abelards** [comment]
@ratnanil that's more a jekyll than a remark issue, sadly I don't have the code handy.

What I did was putting the talks in a /talks folder, so it's not in _drafts or _posts.
It fits my use and what I wanted for URLs since my "talks" somehow live their lives independently of "posts".

If you want directories with jekyll doing its magic, you specify that in the config file (see the very bottom of that page  https://jekyllrb.com/docs/structure/ ). I'm not sure about letting your remarks in _posts folder and then telling jekyll not to change them, but I guess that's possible.

Cheers

**Comment by idbrii** [comment]
As far as I can tell, you cannot *easily* use remarkjs to write markdown files with jekyll. If you create a markdown file with frontmatter, jekyll will process the frontmatter but also process the rest of the markdown in the file -- which messes with your remarkjs slideshow. I didn't have success using `{{ content }}` or `{{ page.content }}` with jekyll on Github Pages. I managed to figure out two ways to make it work:

1. use one md file for the post and another for the slideshow content ([as suggested above](https://github.com/gnab/remark/issues/413#issuecomment-285914769))
2. create a `talks/` directory and put html remarkjs files in it. You'll have to manually maintain an index.

Here's the complete details of the files you need. I'll add some of this to the wiki. This worked for me in github pages, but possibly things are different if you're using a newer version of Jekyll?

# remarkjs as pages

### _layouts/presentation.html

Create a layout for your presentations. Unlike most remarkjs pages, this
doesn't have a `<textarea>` and instead uses a link to a markdown file.

```html
<!DOCTYPE html>
<!-- https://github.com/gnab/remark/issues/413 --->
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ page.title | strip_html }}</title>
    <style>
      @import url(https://fonts.googleapis.com/css?family=Lato);
      @import url(https://fonts.googleapis.com/css?family=Roboto+Mono);

      body {font-family: 'Lato';}
      h1, h2, h3 {font-family: 'Lato'; font-weight: normal; font-weight: 400; margin-bottom: 0;}
      .remark-code, .remark-inline-code { font-family: 'Roboto Mono'; }
    </style>
  </head>
  <body>
    <script src="https://remarkjs.com/downloads/remark-latest.min.js">
    </script>
    <script>
      var slideshow = remark.create({
        sourceUrl: '{{site.baseurl}}{{page.remarkjs_source}}'
      });
    </script>
  </body>
</html>
```

### _posts/2025-02-04-coding.md
Create a post for your presentation. It only contains frontmatter because the
actual presentation is in another file.
```markdown
---
layout: presentation
title: Basic Programming Introduction
categories: [slides]
remarkjs_source: /talks/coding.md

---
```

### talks/coding.md
This is your actual remarkjs presentation, but it has no Jekyll frontmatter.

You can name the `talks/` folder whatever you want, but make sure to use the
correct path in `remarkjs_source` in your posts.

```markdown
class: middle, center

# PROGRAMMING?!

What *is* that?

---
class: top, center

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
Computers are not smart, but they are very fast.

--

Computers are *very* good at following instructions.

--

Fast.
```



# html remarkjs files

Instead of two markdown files for each post (in `_posts` and `talks`), you can
create your talks as an html file and maintain your own index.


### talks/index.md
Each time you add a new talk, you add it to this list.
```markdown
---
layout: page
title: Talks
permalink: /talks/

---

* [PROGRAMMING?! What *is* that?](/talks/coding.html)
```

### talks/coding.html
Create talks like this directly in html.
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PROGRAMMING?! What is that?</title>
    <style>
      @import url(https://fonts.googleapis.com/css?family=Lato);
      @import url(https://fonts.googleapis.com/css?family=Roboto+Mono);

      body {font-family: 'Lato';}
      h1, h2, h3 {font-family: 'Lato'; font-weight: normal; font-weight: 400; margin-bottom: 0;}
      .remark-code, .remark-inline-code { font-family: 'Roboto Mono'; }
    </style>
  </head>
  <body>
    <textarea id="source">
class: middle, center

# PROGRAMMING?!

What *is* that?

---
class: top, center

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
Computers are not smart, but they are very fast.

--

Computers are *very* good at following instructions.

--

Fast.
    </textarea>
    <script src="https://remarkjs.com/downloads/remark-latest.min.js">
    </script>
    <script>
      var slideshow = remark.create();
    </script>
  </body>
</html>
```

Now you can link to blah.github.io/talks to view your list of talks. I didn't even need to change _config.yml to make my index.md get converted into html.
