### ISSUE TITLE
"Load unsafe scripts" (browser error  message)

### ISSUE THREAD

**Issue by gcapes** [gnab/remark#418]
I have followed the get-you-started boilerplate example on the [wiki page](https://github.com/gnab/remark/wiki), and I can open my .html file with a browser with no problems. However, when I host [my presentation on github](https://gcapes.github.io/matlab-programming/) I get a warning message about mixed content:

![screenshot](https://raw.githubusercontent.com/gcapes/matlab-programming/master/load_slideshow.png).

How can I fix this issue? I have created a [new repo](https://github.com/gcapes/remark) using the code from [boilerplate-remote.html](https://github.com/gnab/remark/blob/develop/boilerplate-remote.html) (which I have just discovered), but this presentation [has the same problem](https://gcapes.github.io/remark/). What have I done wrong?

I can view [this presentation](https://github.com/asmeurer/python3-presentation) just fine, but can't see what the key difference is between them.

Thanks in advance!

**Comment by tripu** [comment]
@gcapes: that's &ldquo;mixed content&rdquo;, which is forbidden on the web; cf [`developer.mozilla.org/en-US/docs/Web/Security/Mixed_content`](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Mixed_active_content).

The reason those two examples behave differently is that one of them is loaded over HTTPS, and the other one over HTTP. The former is supposed to be used only for encrypted content, therefore cannot fetch scripts or other dynamic content over the less secure HTTP protocol. The solution is to load [`https://remarkjs.com/downloads/remark-latest.min.js`](https://remarkjs.com/downloads/remark-latest.min.js) instead of [`http://remarkjs.com/downloads/remark-latest.min.js`](http://remarkjs.com/downloads/remark-latest.min.js).

**Comment by tripu** [comment]
Or rather, download  
`https://remarkjs.com/downloads/remark-latest.min.js`  
instead of  
`https://gnab.github.io/remark/downloads/remark-latest.min.js`  
[here](https://github.com/gcapes/matlab-programming/blob/master/docs/index.html#L262).

The latter redirects to `http://remarkjs.com/downloads/remark-latest.min.js` (nb: HTTP), and that causes the &ldquo;mixed content&rdquo;.

**Comment by gcapes** [comment]
Hi @tripu, thanks for the quick reply. Your second reply covers the point that I'd missed (i.e. https://gnab.github.io/remark/downloads/remark-latest.min.js redirects to http). 

So, my remaining question is, how the hell do you know this? If I click on https://gnab.github.io/remark/downloads/remark-latest.min.js, my browser redirects to https://remarkjs.com/downloads/remark-latest.min.js (HTTPS). If this is actually http somehow, that explains the mixed content problem, but I'd like to know how I could verify this.

**Comment by gcapes** [comment]
Thank you so much! That's certainly fixed the problem https://gcapes.github.io/remark/
I would however, still like to understand the solution.

**Comment by tripu** [comment]
@gcapes: I see this double redirection on the developer tools of my browser, when I load `https://gnab.github.io/remark/downloads/remark-latest.min.js`:

![image](https://cloud.githubusercontent.com/assets/1016538/23949451/85dea996-0987-11e7-8b56-da3bd3cc13dc.png)

That's how I knew it was HTTP.

**Comment by tripu** [comment]
@gcapes: you're welcome!
[The wiki page](https://github.com/gnab/remark/wiki#getting-started) seems OK&hellip; That snippet shows `https://remarkjs.com/downloads/remark-latest.min.js`.

**Comment by gcapes** [comment]
I must have initially copied the code from the README file. That snippet shows `https://gnab.github.io/remark/downloads/remark-latest.min.js`.
I thought I'd gone mad for a moment there!
