### ISSUE TITLE
Adding executable JavaScript code blocks

### ISSUE THREAD

**Issue by geluso** [gnab/remark#465]
Any interest in allowing JavaScript code blocks to become executable? I've implemented a simple version of this already. Clicking on a JavaScript code block uses `eval()` to execute the code, and redirects the output from console.log to appended text at the end of the code block.

Right now every code block is self-contained. Defining a function in one code block won't be accessible in another code block. This behavior could definitely be configured so code blocks are accessible between each other on a per-slide level, or in some global-level section.

See it in action: http://5tephen.com/slideshow/slideshow.html#3

See the changes here: https://github.com/geluso/remark/commit/5dbb1de8e090f7090701c88d1e508a34db4f24ac

Is anyone interested in something like this?

**Comment by tripu** [comment]
`eval()` is strongly discouraged (but I understand this may be impossible without it).

We may be opening a security hole if someone copies a chunk of Markdown, or an entire HTML page containing a Remark presentation, to their own domain, and run those blocks of JS: users without good knowledge of how security sandboxes work may execute malicious snippets. We can't rely on users reading and understanding the code before clicking it because the attacker may have hidden malicious statements via CSS, for example.

I'm not rejecting the proposal entirely, only raising security concerns to discuss and see what others think :)

**Comment by geluso** [comment]
Totally. Thanks for the response. I'm absolutely interested in hearing more of the security concerns. I know eval can be extremely dangerous, but it doesn't seem totally bad when I host presentations on my own domain. I'm not evil! Maybe including eval would open some hole for someone to inject malicious JS even when linking to a presentation on my own domain. I just don't know.

Security concerns aside I'm also curious to hear if anyone else yearns for this feature. It's a small target in that it affects only JS code blocks, and it's most effective for ones with small output.

I like having it in my own presentations because I do lots of teaching and it's nice to click on something and prove that it works, or ask students to reason about what the output of something will be before it's executed.

Thanks again for responding!

**Comment by tripu** [comment]
While we wait for others to weigh in, have you considered simply revealing the output or the solution on your slides, @geluso? Not actually evaluating any code on the fly, but pasting the output when you're working on your presentations, and hiding it with `--` initially, so that your students can guess before it's shown to them&hellip;
