### ISSUE TITLE
Disable scaling for a single slide (or, how do prevent embedded code editor from resizing?)

### ISSUE THREAD

**Issue by hmemcpy** [gnab/remark#493]
Hello,
I'm trying to embed a [Scala online REPL](scastie.scala-lang.org) into my slides.
Unfortunately, it seems that when it gets rendered, it gets scaled beyond the proportions of the slide.
See example here: https://codepen.io/hmemcpy/full/goGEme/

Unfortunately, I'm not good with c̶o̶m̶p̶u̶t̶e̶r̶CSS, is there anything I can do to prevent this editor from being resized?

Thank you!

**Comment by tripu** [comment]
@hmemcpy, this is not an answer to your question, but (hopefully) a hacky workaround:

You can style the additional `div` that Scastie creates (are you sure you're using it properly?); something like this will do:

```css
.scastie.embedded {
  position: fixed;
  top: 6rem;
  bottom: 4rem;
  overflow: auto;
}
```

By the way, close your empty `div` (or it won't be used):

```html
### Embedded
<div id="embedded-code"></div>
```

See [my fork of your pen](https://codepen.io/tripu/pen/aEEKWj)

**Comment by 3stadt** [comment]
Hi,
I want to add something to the issue.
Your fix for the scaling works great, @tripu :)

Currently I'm embedding an [ace editor](https://ace.c9.io/) in a [remark presentation](http://presla.io), and a problem that shows in the [forked pen](https://codepen.io/tripu/pen/aEEKWj) as well is: When clicking inside the editor, the cursor is not positioned where the click occured, but some lines off.

I poked around, but without luck so far. I would be glad if someone could give me some hints where to start searching for a fix.
Since the error occurs in the codepen as well I guess it has something to do with the zoom, but currently I'm lost.

Any suggestions? :)

**Comment by abelards** [comment]
Hi @3stadt -- I feel your problem because I've used Ace Editor a lot, a few years ago.

It's Ace-specific, and quite complicated IIRC: Ace does an IFRAME with weird layers of characters for coloring, editing and so on. You have to force dimensions or have a look at Ace's doc to see if a fix is possible. You should find some StackOverflow with people fighting over positioning / mouse events too.

@hmemcpy's problem is fixed by @tripu's workaround, so I'm closing the ticket.
@3stadt if you still consider it's a remark problem, please open another issue with "ACE" in the title.
