### ISSUE TITLE
Easier way to animate bullet points?

### ISSUE THREAD

**Issue by utdrmac** [gnab/remark#515]
Does anyone here have suggestions for an easier way to "animate" or "per-slide" a list of bullet points? This is my current solution:

```
---

## Virtual Machines

* Simulate physical machine
--

* Provide local file system
--

* Accessible over network
--

* Full/independent OS ("guest")
--

* Virtualized device drivers
--

* Resource and memory management
--

* Requires a hypervisor
```

This shows 1 bullet point on each click to the next slide. I have countincrementslides off so that's not an issue. The above just makes the source/Markdown look cumbersome. I am hoping for a `class:` that I can add to the slide that will auto-make them individual slides.

Better yet would be a way to make all of the above 1 slide, but with transitions between each bullet point using animate.css. If you add animate to the main slide class, you get the animation on the entire slide each click instead of on the individual text lines.

**Comment by utdrmac** [comment]
*bump* Wondering if anyone has thought about this. I imagine this would have to be done as a plugin/code to turn each outer-level bullet into a slide page.

**Comment by abelards** [comment]
I feel you @utdrmac, I guess you want something like "tell the whole list to sub-slide each bullet point" but the simplest I can imagine is below (a CSS class).

Still, I think users who want this will reach the same trick, even if it takes a few steps of trial and errors. So it's easier for them to do just that, than for us to add the feature, document it, and for users to learn this by rote.

Also I'm reluctant to make anything "too strict" like "all the bullets on one page" because there will always be someone that has two lists, or will want 1 step, 1 step, then 2 steps at once... and our feature will be useless and they'll have to use your trick anyway.

So while I totally understand your need, I think I will close the ticket.

```
# title

.bullets-as-sub-slides[
* bullet 1
* bullet 2
* bullet 3
]
```
