### ISSUE TITLE
how to use emoji in remark.js ?

### ISSUE THREAD

**Issue by pinkomeo** [gnab/remark#521]
Hi, thanks for your awesome work.
I wonder how to use emoji in my .md file ?
I try `:dog:` but it didn't work...

**Comment by wildcard** [comment]
@pinkomeo check my PR in `remarker` project https://github.com/kt3k/remarker/pull/11

**Comment by abelards** [comment]
Hi all, thanks for everything!

@pinkomeo @sauloperez I'm closing the ticket since it looks fixed.

@wildcard @kt3k remarker looks cool, thanks! I added it to our wiki, tell me if you think I should describe or classify it differently https://github.com/gnab/remark/wiki/Integration-with-external-libraries-and-tools

**Comment by kt3k** [comment]
@abelards Thanks for mentioning my tool!! The description looks nice!
