### ISSUE TITLE
slide.title not set on 'slidein' event

### ISSUE THREAD

**Issue by runeflobakk** [gnab/remark#54]
I have the following code to trigger when slides are shown:

``` javascript
var remark = remark.create();

remark.on("slidein", function(slide, slideIndex) {
   // slide.title is always ""
});
```

One of my slides contains `name: slidename`, but slide.title in my function is always an empty string. Or is there some other way to recognize the slide by name? I don't want to use the slideIndex because that may change.

**Comment by jlegewie** [comment]
Hi,

what is the status of this? I didn't find anything about steps in the wiki but this issue is closed.

Background: I am the author of the [d3js plugin for Reveal.js](https://github.com/jlegewie/reveal.js-d3js-plugin). It relies on fragments in reveal.js, which are basically what you suggest for remark.js. There are two additional things that I find useful:

- Support for `data-...` attributes. In my plugin, I use them to specify the html file that contains the d3.js animation (e.g. `data-file="Collision-Detection.html"`)
- Some `ready` event when remark.js is done and everything is ready to go.
