### ISSUE TITLE
Where is out/remark.js from boilerplate-local.html?

### ISSUE THREAD

**Issue by mevsme** [gnab/remark#553]
Looking forward times when people will use node to print out hello world in a local single webpage. Jeez, modern js community is sick.

**Comment by abelards** [comment]
Hi @mevsme -- I'm not sure what you're looking for. Can you tell me more?

**Comment by dvberkel** [comment]
I am not sure what @mevsme means. But I do know where `out/remark.js` is that `boilerplate-local.html` is referencing.

When building remark an `out` directory is generated which will be populated with various artifacts, among them `out/remark.js`.
So if you want to use the `boilerplate-local.html` instead of the suggested method which can be found on the [README](https://github.com/gnab/remark#getting-started), you need to fetch remark in some other way.

E.g. with this script

```bash
mkdir out && wget https://remarkjs.com/downloads/remark-latest.min.js -o out/remark.js
```

**Comment by peterj** [comment]
Would updating the README with the script @dvberkel mentioned make this it clearer?
