### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jans23** [gnab/remark#571]
Because there hasn't been any new release, I still use remark from 2016 which is published [here](https://remarkjs.com/downloads/remark-latest.min.js) and which is described to be used in the README. I see several newer commits but no newer release. Is the Remark project half-dead or has the recommended way how to use Remark been changed? Of course I could compile the remark.js file myself but I would prefer a more "official" way.

**Comment by yihui** [comment]
You can follow the thread #548 instead of filing a new issue (I also suggested a new release there). I guess the maintainer has already had enough pressure on his shoulders. As a maintainer of several relatively popular open-source projects (including one based on remark.js), I often feel drowned in the numerous Github issues every day, so let's try our best to help @gnab relax and hopefully come back eventually :)
