### ISSUE TITLE
Why this project name?

### ISSUE THREAD

**Issue by kud** [gnab/remark#631]
Hello,

Is there a reason this project is called the same that https://github.com/remarkjs/remark?

I use both and to be fair, it could be confusing sometimes when you want to check the API and see you're on the wrong project.

**Comment by mschilli87** [comment]
@Kud: Well, both projects seem to have started around the same time (just a few months difference) in 2011. I guess at the time nobody noew abut the other project and the name clash was just a coincidence. Changing it now also would not come without confusion and complications downstream, so that might be the reasson the status quo is kept as-is.

**Comment by kud** [comment]
Yeah I totally understand. It's just that the other remark project took lots of popularity, mostly since next.js / gatsby.

I don't know what's the best yeah. But thank you very much for the explanation! Sounds legit!

**Comment by johnbeech** [comment]
Answer found; worth closing the issue? :) - I found this remark project searching for a way to present slides from markdown.

**Comment by kud** [comment]
Yep :)
